package sim.ai.actions;

public enum AIActionType {
    ATTACK_AIRBASE_STRUCTURE,
    ATTACK_GROUND_UNIT,
    ATTACK_AIR_DEFENCE,
    INTERCEPT_FLIGHT,
    DEFEND_AIRBASE_STRUCTURE,
    DEFEND_GROUND_UNIT,
    DEFEND_AIR_DEFENCE,
    TRANSPORT_GROUND_UNIT,
    TRANSPORT_AIR_DEFENCE,
    STRATEGIC_BOMBING,
    NOTHING
}
